# -*- coding: utf-8 -*-
"""mini project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJMk9hHg3j9eDu-1kRGrYg1eO_h3jJAb
"""

!pip install pyspark
import pandas as pd
from pyspark.sql import SparkSession
import matplotlib.pyplot as plt
import seaborn as sns

#Creating sample dataset:
data={
    "product":["Laptop","Phone","Tablet","Laptop","Phone","Tablet"],
    "Price": [1200,800,600,1300,900,650],
    "Quantity":[2,3,4,1,2,5]
}
df=pd.DataFrame(data)
df

#save dataset as CSV:
df.to_csv("sales_data.csv",index=False)

#Create Spark Session:
Spark=SparkSession.builder.appName("ReadDataProject").getOrCreate()
#Load Dataset using spark:
spark_df=Spark.read.csv("sales_data.csv",header=True,inferSchema=True)
spark_df.show()

#Display Dataset Structure:
spark_df.printSchema()

#Basic data processing
spark_df.select("product","Price").show()

#filter data
spark_df.filter(spark_df["Price"]>800).show()

#Calculate Revenue:
from pyspark.sql.functions import col
spark_df=spark_df.withColumn("Revenue",col("Price")*col("Quantity"))
spark_df.show()

#Product Sales Analysis:
product_sales=spark_df.groupBy("product").agg({"Quantity":"sum","Revenue":"sum"})
product_sales.show()
product_sales_1=spark_df.groupBy("product").sum("Revenue")
product_sales_1.show()

#converting to pandas for visualization:
sales_pd=product_sales.toPandas()
sales_pd

#Visualization:
plt.bar(sales_pd["product"],sales_pd["sum(Revenue)"])
plt.title("Product Revenue Analysis")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.show()

plt.figure(figsize=(6,6))

plt.pie(
    sales_pd["sum(Revenue)"],
    labels=sales_pd["product"],
    autopct="%1.1f%%"
)

plt.title("Product Revenue Distribution")

plt.show()

#Save Processed Data:
sales_pd.to_csv("product_sales.csv",index=False)
print("Sales report saved successfully")